CREATE TABLE student.student (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(50) DEFAULT NULL COMMENT '学号',
  name VARCHAR(50) DEFAULT NULL COMMENT '姓名',
  sex INT(11) DEFAULT NULL COMMENT '性别',
  birthday DATE DEFAULT NULL COMMENT '出生日期',
  origin VARCHAR(50) DEFAULT NULL COMMENT '籍贯',
  dept VARCHAR(50) DEFAULT NULL COMMENT '所属系',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '学生信息表';